// Key players for each NBA team - used for Finals MVP autocomplete
// Updated April 16, 2026 — sourced from ESPN rosters

export const TEAM_PLAYERS: Record<string, string[]> = {
  // --- WESTERN CONFERENCE ---
  OKC: [
    "Shai Gilgeous-Alexander",
    "Jalen Williams",
    "Chet Holmgren",
    "Lu Dort",
    "Isaiah Hartenstein",
    "Alex Caruso",
    "Aaron Wiggins",
    "Kenrich Williams",
    "Cason Wallace",
    "Isaiah Joe",
    "Jared McCain",
    "Nikola Topic",
    "Ajay Mitchell",
    "Jaylin Williams",
    "Payton Sandfort",
  ],
  SAS: [
    "Victor Wembanyama",
    "De'Aaron Fox",
    "Devin Vassell",
    "Stephon Castle",
    "Harrison Barnes",
    "Keldon Johnson",
    "Dylan Harper",
    "Julian Champagnie",
    "Luke Kornet",
    "Kelly Olynyk",
    "Emanuel Miller",
    "Harrison Ingram",
    "Jordan McLaughlin",
    "Mason Plumlee",
  ],
  DEN: [
    "Nikola Jokic",
    "Jamal Murray",
    "Aaron Gordon",
    "Christian Braun",
    "Cameron Johnson",
    "Bruce Brown",
    "Peyton Watson",
    "Julian Strawther",
    "Jonas Valanciunas",
    "Tim Hardaway Jr.",
    "Tyus Jones",
    "DaRon Holmes II",
    "Zeke Nnaji",
    "KJ Simpson",
  ],
  LAL: [
    "Luka Doncic",
    "LeBron James",
    "Austin Reaves",
    "Marcus Smart",
    "Deandre Ayton",
    "Rui Hachimura",
    "Dalton Knecht",
    "Jaxson Hayes",
    "Maxi Kleber",
    "Jarred Vanderbilt",
    "Bronny James",
    "Nick Smith Jr.",
    "Luke Kennard",
    "Jake LaRavia",
  ],
  HOU: [
    "Kevin Durant",
    "Fred VanVleet",
    "Alperen Sengun",
    "Jabari Smith Jr.",
    "Amen Thompson",
    "Reed Sheppard",
    "Clint Capela",
    "Tari Eason",
    "Steven Adams",
    "Dorian Finney-Smith",
    "Jeff Green",
    "Aaron Holiday",
    "Josh Okogie",
    "Jae'Sean Tate",
  ],
  MIN: [
    "Anthony Edwards",
    "Julius Randle",
    "Rudy Gobert",
    "Jaden McDaniels",
    "Mike Conley",
    "Donte DiVincenzo",
    "Naz Reid",
    "Ayo Dosunmu",
    "Terrence Shannon Jr.",
    "Bones Hyland",
    "Joe Ingles",
    "Kyle Anderson",
    "Rocco Zikarsky",
  ],
  POR: [
    "Damian Lillard",
    "Scoot Henderson",
    "Jrue Holiday",
    "Deni Avdija",
    "Shaedon Sharpe",
    "Donovan Clingan",
    "Jerami Grant",
    "Toumani Camara",
    "Robert Williams III",
    "Kris Murray",
    "Matisse Thybulle",
    "Vit Krejci",
    "Blake Wesley",
  ],
  // --- EASTERN CONFERENCE ---
  DET: [
    "Cade Cunningham",
    "Ausar Thompson",
    "Tobias Harris",
    "Jalen Duren",
    "Kevin Huerter",
    "Isaiah Stewart",
    "Ronald Holland II",
    "Caris LeVert",
    "Marcus Sasser",
    "Duncan Robinson",
    "Paul Reed",
    "Wendell Moore Jr.",
  ],
  BOS: [
    "Jayson Tatum",
    "Jaylen Brown",
    "Derrick White",
    "Payton Pritchard",
    "Nikola Vucevic",
    "Sam Hauser",
    "Baylor Scheierman",
    "Neemias Queta",
    "Dalano Banton",
    "Ron Harper Jr.",
    "Jordan Walsh",
  ],
  NYK: [
    "Jalen Brunson",
    "Karl-Anthony Towns",
    "Mikal Bridges",
    "OG Anunoby",
    "Josh Hart",
    "Miles McBride",
    "Mitchell Robinson",
    "Jordan Clarkson",
    "Jose Alvarado",
    "Tyler Kolek",
    "Landry Shamet",
    "Jeremy Sochan",
    "Dillon Jones",
  ],
  CLE: [
    "Donovan Mitchell",
    "James Harden",
    "Evan Mobley",
    "Jarrett Allen",
    "Max Strus",
    "Sam Merrill",
    "Dennis Schroder",
    "Keon Ellis",
    "Dean Wade",
    "Craig Porter Jr.",
    "Larry Nance Jr.",
    "Jaylon Tyson",
  ],
  TOR: [
    "Scottie Barnes",
    "RJ Barrett",
    "Brandon Ingram",
    "Immanuel Quickley",
    "Jakob Poeltl",
    "Jamal Shead",
    "Ja'Kobe Walter",
    "Gradey Dick",
    "Trayce Jackson-Davis",
    "Jonathan Mogbo",
  ],
  ATL: [
    "Jalen Johnson",
    "Dyson Daniels",
    "Zaccharie Risacher",
    "CJ McCollum",
    "Onyeka Okongwu",
    "Corey Kispert",
    "Nickeil Alexander-Walker",
    "Jonathan Kuminga",
    "Buddy Hield",
    "Gabe Vincent",
    "Jock Landale",
    "Mouhamed Gueye",
    "Asa Newell",
  ],
  PHI: [
    "Tyrese Maxey",
    "Joel Embiid",
    "Paul George",
    "Kelly Oubre Jr.",
    "VJ Edgecombe",
    "Andre Drummond",
    "Quentin Grimes",
    "Kyle Lowry",
    "Adem Bona",
    "Johni Broome",
    "Justin Edwards",
    "Dalen Terry",
    "Trendon Watford",
  ],
  // --- PLAY-IN 8-SEED CONTENDERS ---
  PHX: [
    "Devin Booker",
    "Jalen Green",
    "Dillon Brooks",
    "Royce O'Neale",
    "Mark Williams",
    "Khaman Maluach",
    "Ryan Dunn",
    "Oso Ighodaro",
    "Grayson Allen",
    "Haywood Highsmith",
    "Rasheer Fleming",
    "Koby Brea",
  ],
  GSW: [
    "Stephen Curry",
    "Brandin Podziemski",
    "Kristaps Porzingis",
    "Al Horford",
    "Draymond Green",
    "Jimmy Butler III",
    "Gary Payton II",
    "Moses Moody",
    "Seth Curry",
    "De'Anthony Melton",
    "Pat Spencer",
    "Gui Santos",
    "Quinten Post",
  ],
  ORL: [
    "Paolo Banchero",
    "Franz Wagner",
    "Jalen Suggs",
    "Wendell Carter Jr.",
    "Jonathan Isaac",
    "Desmond Bane",
    "Goga Bitadze",
    "Moritz Wagner",
    "Anthony Black",
    "Tristan da Silva",
    "Jevon Carter",
    "Jett Howard",
    "Jamal Cain",
    "Colin Castleton",
    "Alex Morales",
    "Noah Penda",
    "Jase Richardson",
  ],
  CHA: [
    "LaMelo Ball",
    "Brandon Miller",
    "Kon Knueppel",
    "Coby White",
    "Miles Bridges",
    "Tre Mann",
    "Grant Williams",
    "Pat Connaughton",
    "Josh Green",
    "Tidjane Salaun",
    "Liam McNeeley",
    "Ryan Kalkbrenner",
  ],
};

export function getPlayersForTeams(teamAbbrs: string[]): string[] {
  const players: string[] = [];
  for (const abbr of teamAbbrs) {
    const teamPlayers = TEAM_PLAYERS[abbr];
    if (teamPlayers) {
      players.push(...teamPlayers);
    }
  }
  return players;
}

export function searchPlayers(query: string, teamAbbrs: string[]): string[] {
  if (!query.trim()) return [];
  const available = getPlayersForTeams(teamAbbrs);
  const q = query.toLowerCase();
  return available.filter((p) => p.toLowerCase().includes(q));
}
